#!/bin/bash
set -e

CW="/c/Program Files (x86)/Freescale/CW for MPC55xx and MPC56xx 2.10/PowerPC_EABI_Tools/Command_Line_Tools"
KAMEK_STDLIB="/c/Users/naari/src/github.com/Treeki/Kamek/k_stdlib"
KAMEK="/c/Users/naari/src/github.com/Treeki/Kamek/Kamek.exe"
PATCH_DIR="$(cd "$(dirname "$0")" && pwd)"
export PATCH_DIR

# 1. Run per-feature generators (gen_*.py in each feature dir)
echo "=== Running feature generators ==="
shopt -s nullglob
for gen in "$PATCH_DIR"/features/*/gen_*.py; do
    # Only run headers-from-data style generators (not mod/yaml-from-yaml)
    case "$(basename "$gen")" in
        gen_*_header.py) python3 "$gen" ;;
    esac
done
shopt -u nullglob

# 2. Discover all source files
SOURCES=()
for src in "$PATCH_DIR"/common/*.cpp "$PATCH_DIR"/features/*/*.cpp; do
    [ -f "$src" ] && SOURCES+=("$src")
done
echo "Sources: ${SOURCES[@]#$PATCH_DIR/}"

# 3. Compile
echo "=== Compiling ==="
OBJS=()
for src in "${SOURCES[@]}"; do
    obj="${src%.cpp}.o"
    feature_inc="$(dirname "$src")"
    "$CW/mwcceppc.exe" \
        -I- -i "$KAMEK_STDLIB" -i "$PATCH_DIR/common" -i "$feature_inc" \
        -Cpp_exceptions off -enum int -Os \
        -use_lmw_stmw on -fp hard -rostr \
        -sdata 0 -sdata2 0 \
        -c -o "$obj" "$src"
    OBJS+=("$obj")
done

# 4. Link with Kamek
echo "=== Linking ==="
"$KAMEK" \
    "${OBJS[@]}" \
    -static=0x806ED000 \
    -externals="$PATCH_DIR/externals.txt" \
    -output-gecko="$PATCH_DIR/mkgp2_patch_gecko.txt" \
    -output-riiv="$PATCH_DIR/mkgp2_patch_riiv_raw.xml" \
    -output-code="$PATCH_DIR/mkgp2_patch.bin"

# 4.5. Validate ArenaLo > bin_end (heap must not overlap patch tail)
echo "=== Validating ArenaLo ==="
python3 - <<'PY'
import os, re, sys
ROOT = os.environ.get("PATCH_DIR") or os.path.dirname(os.path.abspath(__file__))
LOAD_ADDR = 0x806ED000  # keep in sync with build.sh `-static=...`
bin_size = os.path.getsize(os.path.join(ROOT, "mkgp2_patch.bin"))
bin_end  = LOAD_ADDR + bin_size
src = open(os.path.join(ROOT, "common", "patch_common.cpp"), encoding="utf-8").read()
m = re.search(r"kmWrite32\s*\(\s*0x80000030\s*,\s*(0x[0-9A-Fa-f]+)\s*\)", src)
if not m:
    print("ERROR: cannot find ArenaLo kmWrite32 in common/patch_common.cpp", file=sys.stderr); sys.exit(1)
arena_lo = int(m.group(1), 16)
margin   = arena_lo - bin_end
if margin < 0:
    suggested = (bin_end + 0xFFFF) & ~0xFFFF  # round up to next 0x10000
    print(f"ERROR: patch bin end 0x{bin_end:08X} > ArenaLo 0x{arena_lo:08X} ({-margin} byte overflow)", file=sys.stderr)
    print(f"       Heap will overwrite patch data tail. Raise ArenaLo to >= 0x{suggested:08X}", file=sys.stderr)
    print(f"       Edit common/patch_common.cpp: kmWrite32(0x80000030, 0x{suggested:08X});", file=sys.stderr)
    sys.exit(1)
print(f"ArenaLo OK: bin end 0x{bin_end:08X} <= ArenaLo 0x{arena_lo:08X} (margin {margin} bytes)")
PY

# 5. Wrap Riivolution XML
echo "=== Wrapping Riivolution XML ==="
{
  echo '<wiidisc version="1">'
  echo '  <id game="GNLJ"/>'
  echo '  <options>'
  echo '    <section name="MKGP2 Patches">'
  echo '      <option name="Enable" default="1">'
  echo '        <choice name="Enabled">'
  echo '          <patch id="mkgp2_patch"/>'
  echo '        </choice>'
  echo '      </option>'
  echo '    </section>'
  echo '  </options>'
  echo '  <patch id="mkgp2_patch">'
  while IFS= read -r line || [ -n "$line" ]; do
    echo "    $line"
  done < "$PATCH_DIR/mkgp2_patch_riiv_raw.xml"
  # Per-feature <file> fragments (generated by gen_*_header.py scripts).
  shopt -s nullglob
  for frag in "$PATCH_DIR"/features/*/generated_riivolution.xml; do
    while IFS= read -r line || [ -n "$line" ]; do
      [ -z "$line" ] && continue
      echo "    $line"
    done < "$frag"
  done
  shopt -u nullglob
  echo '  </patch>'
  echo '</wiidisc>'
} > "$PATCH_DIR/mkgp2_patch.xml"

RIIV_ROOT="/c/Users/naari/Documents/Dolphin Emulator/Load/Riivolution"
RIIV_DIR="$RIIV_ROOT/riivolution"
RIIV_FILES_DIR="$RIIV_ROOT/mkgp2_patch"
mkdir -p "$RIIV_DIR" "$RIIV_FILES_DIR"
cp "$PATCH_DIR/mkgp2_patch.xml" "$RIIV_DIR/mkgp2_patch.xml"

# Copy feature-supplied asset files to the Riivolution asset root.
shopt -s nullglob
for asset in "$PATCH_DIR"/features/*/files/*; do
    [ -f "$asset" ] && cp "$asset" "$RIIV_FILES_DIR/"
done
shopt -u nullglob

# 6. Generate patch_map.md
echo "=== Generating patch_map.md ==="
python3 "$PATCH_DIR/tools/gen_patch_map.py"

echo "=== Done ==="
echo "Riivolution: $RIIV_DIR/mkgp2_patch.xml"
echo "Asset dir:   $RIIV_FILES_DIR"
echo "Gecko:       $PATCH_DIR/mkgp2_patch_gecko.txt"
echo "Patch map:   $PATCH_DIR/patch_map.md"
