#!/usr/bin/env python3
"""Generate generated_custom_assets.h from assets.yaml + bindings/*.yaml.

Output (included once from custom_assets.cpp):
  - kCustomResourceTable[]  CustomResourceEntry records (40 bytes each)
  - kCustomResourceCount
  - kBindings[]             CupBinding records (8 bytes each)
  - kBindingCount

Schemas are documented in assets.yaml / bindings/*.yaml headers.
"""

import sys
from pathlib import Path

import yaml


FEATURE_DIR = Path(__file__).resolve().parent
ASSETS_YAML = FEATURE_DIR / "assets.yaml"
BINDINGS_DIR = FEATURE_DIR / "bindings"
OUTPUT = FEATURE_DIR / "generated_custom_assets.h"

CUSTOM_ID_BASE = 0x9000
U16_MAX = 0xFFFF


def fatal(msg):
    print(f"gen_custom_assets: ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def require_u16(name, value):
    if not isinstance(value, int):
        fatal(f"{name}: expected int, got {type(value).__name__} ({value!r})")
    if not (0 <= value <= U16_MAX):
        fatal(f"{name}: 0x{value:x} out of u16 range")
    return value


def require_xy(name, value, default=None):
    if value is None:
        if default is None:
            fatal(f"{name}: required")
        return default
    if not (isinstance(value, (list, tuple)) and len(value) == 2):
        fatal(f"{name}: expected [x, y], got {value!r}")
    return (float(value[0]), float(value[1]))


def load_assets():
    if not ASSETS_YAML.exists():
        fatal(f"missing {ASSETS_YAML}")
    doc = yaml.safe_load(ASSETS_YAML.read_text(encoding="utf-8")) or {}
    raw = doc.get("assets") or []
    if not isinstance(raw, list):
        fatal("assets.yaml: 'assets' must be a list")
    seen_ids = {}
    out = []
    for i, a in enumerate(raw):
        loc = f"assets.yaml#assets[{i}]"
        if not isinstance(a, dict):
            fatal(f"{loc}: entry must be a mapping")
        rid = a.get("id")
        if rid is None:
            fatal(f"{loc}: 'id' required")
        rid = require_u16(f"{loc}.id", rid)
        if rid < CUSTOM_ID_BASE:
            fatal(f"{loc}.id=0x{rid:x}: custom ids must be >= 0x{CUSTOM_ID_BASE:x}")
        if rid in seen_ids:
            fatal(f"{loc}.id=0x{rid:x}: duplicate (also at {seen_ids[rid]})")
        seen_ids[rid] = loc

        gk = a.get("group_key")
        if gk is None:
            fatal(f"{loc}: 'group_key' required")
        gk = require_u16(f"{loc}.group_key", gk)

        size = require_xy(f"{loc}.size", a.get("size"))
        offset = require_xy(f"{loc}.offset", a.get("offset"), default=(0.0, 0.0))
        scale  = require_xy(f"{loc}.scale",  a.get("scale"),  default=(1.0, 1.0))
        slot_index = a.get("slot_index", 0)
        if not (-0x8000 <= slot_index <= 0x7FFF):
            fatal(f"{loc}.slot_index={slot_index} out of s16 range")
        next_id = a.get("next_id", -1)
        if not (-0x8000 <= next_id <= 0x7FFF):
            fatal(f"{loc}.next_id={next_id} out of s16 range")
        flags = a.get("flags", 4)
        if not (0 <= flags <= 0xFF):
            fatal(f"{loc}.flags={flags} out of u8 range")

        out.append({
            "id":         rid,
            "group_key":  gk,
            "slot_index": slot_index,
            "next_id":    next_id,
            "flags":      flags,
            "offset":     offset,
            "size":       size,
            "scale":      scale,
        })
    return out


def load_bindings():
    out = []
    if not BINDINGS_DIR.exists():
        return out
    files = sorted(BINDINGS_DIR.glob("*.yaml"))
    for f in files:
        doc = yaml.safe_load(f.read_text(encoding="utf-8")) or {}
        cup_id = doc.get("cup_id")
        if cup_id is None:
            cup_s16 = -1
        else:
            if not isinstance(cup_id, int) or not (-0x8000 <= cup_id <= 0x7FFF):
                fatal(f"{f.name}: cup_id={cup_id} out of s16 range")
            cup_s16 = cup_id
        reps = doc.get("replacements") or []
        if not isinstance(reps, list):
            fatal(f"{f.name}: replacements must be a list")
        for i, r in enumerate(reps):
            loc = f"{f.name}#replacements[{i}]"
            if not isinstance(r, dict) or "from" not in r or "to" not in r:
                fatal(f"{loc}: expected {{from, to}}")
            frm = require_u16(f"{loc}.from", r["from"])
            to  = require_u16(f"{loc}.to",   r["to"])
            out.append({"cup_id": cup_s16, "from": frm, "to": to, "source": f.name})
    # Sanity: duplicate (cup_id, from) means an ambiguous binding.
    seen = {}
    for b in out:
        key = (b["cup_id"], b["from"])
        if key in seen:
            fatal(f"duplicate binding cup_id={b['cup_id']} from=0x{b['from']:x}: "
                  f"{seen[key]} and {b['source']}")
        seen[key] = b["source"]
    return out


def emit(assets, bindings):
    lines = []
    lines.append("// GENERATED by gen_custom_assets_header.py — do not edit.")
    lines.append("// Source: assets.yaml + bindings/*.yaml")
    lines.append("#ifndef GENERATED_CUSTOM_ASSETS_H")
    lines.append("#define GENERATED_CUSTOM_ASSETS_H")
    lines.append("")
    lines.append('#include "custom_assets.h"')
    lines.append("")

    # Assets
    lines.append(f"const CustomResourceEntry kCustomResourceTable[] = {{")
    for a in assets:
        ox, oy = a["offset"]
        sx, sy = a["size"]
        cx, cy = a["scale"]
        lines.append("    {")
        lines.append(f"        /* self_id    */ 0x{a['id']:04x},")
        lines.append(f"        /* pad_02     */ 0,")
        lines.append(f"        /* offset_x   */ {ox!r}f,")
        lines.append(f"        /* offset_y   */ {oy!r}f,")
        lines.append(f"        /* size_x     */ {sx!r}f,")
        lines.append(f"        /* size_y     */ {sy!r}f,")
        lines.append(f"        /* slot_index */ {a['slot_index']},")
        lines.append(f"        /* group_key  */ 0x{a['group_key']:04x},")
        ni = a["next_id"]
        ni_str = f"0x{ni:04x}" if ni >= 0 else str(ni)
        lines.append(f"        /* next_id    */ {ni_str},")
        lines.append(f"        /* pad_1a     */ 0,")
        lines.append(f"        /* scale_x    */ {cx!r}f,")
        lines.append(f"        /* scale_y    */ {cy!r}f,")
        lines.append(f"        /* flags      */ {a['flags']},")
        lines.append(f"        /* pad_tail   */ {{0,0,0}},")
        lines.append("    },")
    if not assets:
        # Avoid empty array (ISO C/C++ disallow). Emit a single sentinel entry
        # with an id that CustomResource_Lookup will never match.
        lines.append("    { 0, 0, 0.0f, 0.0f, 1.0f, 1.0f, 0, 0, -1, 0, 1.0f, 1.0f, 0, {0,0,0} }, // sentinel (kCustomResourceCount=0)")
    lines.append("};")
    lines.append(f"const unsigned int kCustomResourceCount = {len(assets)}u;")
    lines.append("")

    # Bindings
    lines.append("const CupBinding kBindings[] = {")
    for b in bindings:
        lines.append(
            f"    {{ /*cupId*/ {b['cup_id']}, "
            f"/*from*/ 0x{b['from']:04x}, "
            f"/*to*/ 0x{b['to']:04x}, "
            f"0 }}, // {b['source']}"
        )
    if not bindings:
        lines.append("    { 0, 0, 0, 0 }, // sentinel (kBindingCount=0)")
    lines.append("};")
    lines.append(f"const unsigned int kBindingCount = {len(bindings)}u;")
    lines.append("")

    lines.append("#endif")
    lines.append("")
    return "\n".join(lines)


def main():
    assets = load_assets()
    bindings = load_bindings()
    OUTPUT.write_text(emit(assets, bindings), encoding="utf-8")
    print(f"Generated {OUTPUT.name}: {len(assets)} asset(s), {len(bindings)} binding(s)")


if __name__ == "__main__":
    main()
