#!/usr/bin/env python3
"""Scan all .cpp sources and emit patch_map.md: a table of every Kamek hook/write
grouped by feature. Feature name = source file basename (or parent dir for features/).
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Patterns for Kamek patch macros (arg positions follow Kamek DSL)
PATTERNS = [
    ("branch",  re.compile(r"\bkmBranch\s*\(\s*(0x[0-9a-fA-F]+)\s*,\s*([A-Za-z_][\w]*)\s*\)")),
    ("call",    re.compile(r"\bkmCall\s*\(\s*(0x[0-9a-fA-F]+)\s*,\s*([A-Za-z_][\w]*)\s*\)")),
    ("bl",      re.compile(r"\bkmCallDefCpp\s*\(\s*(0x[0-9a-fA-F]+)\s*,\s*[^,]+,")),
    ("write32", re.compile(r"\bkmWrite32\s*\(\s*(0x[0-9a-fA-F]+)\s*,\s*([^)]+)\)")),
    ("write16", re.compile(r"\bkmWrite16\s*\(\s*(0x[0-9a-fA-F]+)\s*,\s*([^)]+)\)")),
    ("write8",  re.compile(r"\bkmWrite8\s*\(\s*(0x[0-9a-fA-F]+)\s*,\s*([^)]+)\)")),
    ("patchExit", re.compile(r"\bkmPatchExitPoint\s*\(\s*([A-Za-z_][\w]*)\s*,\s*(0x[0-9a-fA-F]+)\s*\)")),
    ("nop",     re.compile(r"\bkmWriteNOP\s*\(\s*(0x[0-9a-fA-F]+)\s*\)")),
]

def feature_of(path: Path) -> str:
    rel = path.relative_to(ROOT)
    parts = rel.parts
    if parts[0] == "common":
        return "(common)"
    if parts[0] == "features" and len(parts) >= 2:
        return parts[1]
    return rel.stem

def scan():
    hooks = {}  # feature -> list of (kind, addr, detail, src_line)
    for src in sorted(ROOT.glob("common/*.cpp")) + sorted(ROOT.glob("features/*/*.cpp")):
        feature = feature_of(src)
        hooks.setdefault(feature, [])
        for lineno, line in enumerate(src.read_text(encoding="utf-8").splitlines(), 1):
            stripped = line.strip()
            if stripped.startswith("//") or stripped.startswith("/*"):
                continue
            for kind, pat in PATTERNS:
                for m in pat.finditer(line):
                    groups = m.groups()
                    if kind == "patchExit":
                        detail = f"exit={groups[1]} func={groups[0]}"
                        addr = groups[1]
                    elif kind in ("write32", "write16", "write8"):
                        addr, val = groups[0], groups[1].strip()
                        detail = f"value={val}"
                    elif kind == "nop":
                        addr = groups[0]
                        detail = "NOP"
                    else:
                        addr = groups[0]
                        detail = f"target={groups[1]}" if len(groups) > 1 else ""
                    hooks[feature].append((kind, addr, detail, src.relative_to(ROOT).as_posix(), lineno))
    return hooks

def main():
    hooks = scan()
    out = [
        "# Patch Map",
        "",
        "Auto-generated by `tools/gen_patch_map.py` from source scan.",
        "",
    ]
    total = 0
    for feature in sorted(hooks.keys()):
        items = hooks[feature]
        if not items:
            continue
        total += len(items)
        out.append(f"## {feature} ({len(items)} hooks)")
        out.append("")
        out.append("| Kind | Address | Detail | Source |")
        out.append("|------|---------|--------|--------|")
        for kind, addr, detail, src, lineno in sorted(items, key=lambda x: int(x[1], 16)):
            out.append(f"| `{kind}` | `{addr}` | {detail} | `{src}:{lineno}` |")
        out.append("")
    out.insert(3, f"**Total: {total} hooks across {sum(1 for v in hooks.values() if v)} features.**")
    out.insert(4, "")

    (ROOT / "patch_map.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"Generated patch_map.md: {total} hooks")

if __name__ == "__main__":
    main()
